/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectoa;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.util.ArrayList;


/**
 *
 * @author angel-monterroso
 */
public class repaso2 extends javax.swing.JFrame {

    /**
     * Creates new form repaso2
     */
    public repaso2() {
        initComponents();
        TablaModelos();
        TablaDatos();
       // TablaDatos();
    }
    
    private void limpiarCampos() {
        jmarca.setText("");
        jcolor.setText("");
        jmodelo.setText("");
        jlinea.setText("");
      //  selectedRow = -1;
        }
    
    private void TablaModelos() {
        String[] encabezado = {"Marca", "Color", "Modelo", "Linea"};
        DefaultTableModel modelo = new DefaultTableModel(encabezado, 0); // 0 filas iniciales
        jTable1.setModel(modelo);
    }
    
    private void TablaDatos(){
        DefaultTableModel Tabla = (DefaultTableModel) jTable1.getModel();
        Tabla.setRowCount(0); // Limpiar antes de llenar
        
        for (repasohecho repaso2 : ProyectoA.repasoshechos) {
           // for (LibroVendido libro : venta.librosVendidos) {
            Tabla.addRow(new Object[]{
                repaso2.marca,      // Estos campos deben existir en VentaRealizada
                repaso2.color,
                repaso2.modelo,
                repaso2.linea
                
            });
        }
        
}
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Marca = new javax.swing.JLabel();
        Color = new javax.swing.JLabel();
        Modelo = new javax.swing.JLabel();
        Linea = new javax.swing.JLabel();
        jmarca = new javax.swing.JTextField();
        jcolor = new javax.swing.JTextField();
        jmodelo = new javax.swing.JTextField();
        jlinea = new javax.swing.JTextField();
        bnagregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jbeliminar = new javax.swing.JButton();
        jbconsultar = new javax.swing.JButton();
        jbmodificar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Marca.setText("Marca");

        Color.setText("Color");

        Modelo.setText("Modelo");

        Linea.setText("Linea");

        jmarca.setText("jTextField1");

        jcolor.setText("jTextField2");

        jmodelo.setText("jTextField3");

        bnagregar.setText("Agregar");
        bnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bnagregarActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jbeliminar.setText("Eliminar");
        jbeliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbeliminarActionPerformed(evt);
            }
        });

        jbconsultar.setText("Consultar");
        jbconsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbconsultarActionPerformed(evt);
            }
        });

        jbmodificar.setText("Modificar");
        jbmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbmodificarActionPerformed(evt);
            }
        });

        jButton1.setText("Modificar N");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(bnagregar)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Linea)
                                .addComponent(Modelo)
                                .addComponent(Color)
                                .addComponent(Marca))
                            .addGap(45, 45, 45)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jmarca)
                                .addComponent(jcolor)
                                .addComponent(jmodelo)
                                .addComponent(jlinea))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jbconsultar)
                            .addComponent(jbeliminar)
                            .addComponent(jbmodificar)
                            .addComponent(jButton1))
                        .addGap(95, 95, 95)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Marca)
                            .addComponent(jmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Color)
                            .addComponent(jcolor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Modelo)
                            .addComponent(jmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Linea)
                            .addComponent(jlinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addComponent(bnagregar)
                        .addGap(18, 18, 18)
                        .addComponent(jbeliminar)
                        .addGap(18, 18, 18)
                        .addComponent(jbconsultar)
                        .addGap(18, 18, 18)
                        .addComponent(jbmodificar)
                        .addGap(33, 33, 33)
                        .addComponent(jButton1)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bnagregarActionPerformed
  
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    String marca = jmarca.getText();
    String color = jcolor.getText();
    String modelo = jmodelo.getText();
    String linea = jlinea.getText();

    if (marca.isEmpty() || color.isEmpty() || modelo.isEmpty() || linea.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Por favor, complete todos los campos.");
    } else {
        model.addRow(new Object[]{marca, color, modelo, linea});
       limpiarCampos();
    }
     
    
    
   
    }//GEN-LAST:event_bnagregarActionPerformed

    private void jbmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbmodificarActionPerformed

        int fila = jTable1.getSelectedRow();
    if (fila >= 0) {
        TableModel model = jTable1.getModel();
        model.setValueAt(jmarca.getText(), fila, 0);
        model.setValueAt(jcolor.getText(), fila, 1);
        model.setValueAt(jmodelo.getText(), fila, 2);
        model.setValueAt(jlinea.getText(), fila, 3);
        limpiarCampos();
        
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione una fila para modificar.");
    }
    }//GEN-LAST:event_jbmodificarActionPerformed

    private void jbconsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbconsultarActionPerformed

         int fila = jTable1.getSelectedRow();
    if (fila >= 0) {
        TableModel model = jTable1.getModel();
        jmarca.setText(model.getValueAt(fila, 0).toString());
        jcolor.setText(model.getValueAt(fila, 1).toString());
        jmodelo.setText(model.getValueAt(fila, 2).toString());
        jlinea.setText(model.getValueAt(fila, 3).toString());
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione una fila para consultar.");
               limpiarCampos();

    }
    }//GEN-LAST:event_jbconsultarActionPerformed

    private void jbeliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbeliminarActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    int fila = jTable1.getSelectedRow();
    
    int confirm = JOptionPane.showConfirmDialog(this, 
        "¿Estás seguro de que deseas eliminar este modelo?", 
        "Confirmar eliminación", 
        JOptionPane.YES_NO_OPTION);
    if (fila >= 0) {
        model.removeRow(fila);
    } else {
        JOptionPane.showMessageDialog(this, "Seleccione una fila para borrar.");
               limpiarCampos();

    }
    }//GEN-LAST:event_jbeliminarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        int filaSeleccionada = jTable1.getSelectedRow();
        
        if (filaSeleccionada >= 0) {
        repasohecho repaso = ProyectoA.repasoshechos.get(filaSeleccionada);
        
        jmarca.setText(repaso.marca);
        jcolor.setText(repaso.color);
        jmodelo.setText(repaso.modelo);
        jlinea.setText(repaso.linea);
       
        
        JButton btnGuardar = new JButton("Guardar Cambios");
        btnGuardar.addActionListener(e -> {
            
            repaso.marca = jmarca.getText();
            repaso.color = jcolor.getText();
            repaso.modelo = jmodelo.getText();
            repaso.linea = jlinea.getText();
            
            
            limpiarCampos();
            JOptionPane.showMessageDialog(this, "Libro actualizado correctamente");
        });
        
         getContentPane().add(btnGuardar);
        btnGuardar.setBounds(50, 50, 150, 30); // Ajusta la posición según tu diseño
        repaint();
        } else {
        JOptionPane.showMessageDialog(this, "Seleccione un libro para modificar");

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(repaso2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(repaso2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(repaso2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(repaso2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new repaso2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Color;
    private javax.swing.JLabel Linea;
    private javax.swing.JLabel Marca;
    private javax.swing.JLabel Modelo;
    private javax.swing.JButton bnagregar;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbconsultar;
    private javax.swing.JButton jbeliminar;
    private javax.swing.JButton jbmodificar;
    private javax.swing.JTextField jcolor;
    private javax.swing.JTextField jlinea;
    private javax.swing.JTextField jmarca;
    private javax.swing.JTextField jmodelo;
    // End of variables declaration//GEN-END:variables
}
